### ISSUE TITLE
Luacheck.split_match: AttributeError: 'NoneType' object has no attribute 'group'`

### ISSUE THREAD

**Issue by LukeMS** [SublimeLinter/SublimeLinter-luacheck#16]
### Problem

I'm getting an error that is making the linter crash:

`Traceback (most recent call last):
  File "D:\portable\Sublime Text Build 3143\Data\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "D:\portable\Sublime Text Build 3143\Data\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "D:\portable\Sublime Text Build 3143\Data\Packages\SublimeLinter\sublimelinter.py", line 121, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "D:\portable\Sublime Text Build 3143\Data\Packages\SublimeLinter\lint\linter.py", line 968, in lint_view
    linter.lint(hit_time)
  File "D:\portable\Sublime Text Build 3143\Data\Packages\SublimeLinter\lint\linter.py", line 1449, in lint
    for match, line, col, error, warning, message, near in self.find_errors(output):
  File "D:\portable\Sublime Text Build 3143\Data\Packages\SublimeLinter\lint\linter.py", line 1792, in find_errors
    yield self.split_match(self.regex.match(line.rstrip()))
  File "D:\portable\Sublime Text Build 3143\Data\Packages\SublimeLinter-luacheck\linter.py", line 34, in split_match
    col_end = int(match.group(3))
AttributeError: 'NoneType' object has no attribute 'group'`

### A solution
I've removed the `Luacheck.split_match`, falling back to the super's method (like python, ruby, cppcheck - those do not implement its own split method).
That solved the problem for me.

### Notes

1. The traceback's line number is from a modified version I was using for debugging, you should consider the last entry as pointing to line 35.
2. It seems a [pull request](https://github.com/SublimeLinter/SublimeLinter-luacheck/pull/14) implements the same solution (relying on super).

**Comment by kaste** [comment]
This should be working in SL4 which is beta currently.
